after_success: 
- coveralls
addons:
  firefox: "latest"
install:
- pip install coveralls
- make bin/test
env: 
  global: 
    secure: aeJaNydBzTcyBwbbluHDvs8vmryEpwaSFYD+SvTlD2e341Ilye+vxKR2/fT56OYLONEvFXkc5K1maw4caJqaxAfjlfO80Id3FsIO3f/AM/zTl3SERHd//y8CaaokL9vaxqNRjUHRMrpJZQpTFKW8V7HMnK88ulQF8nuM1gaQU/Q=
language: python
before_script: 
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_install: 
- sudo apt-get install libpcre3-dev
- sudo apt-get install python-docutils
- export GECKODRIVER_VERSION=0.21.0
- wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

python: 
- 2.7
after_script: 
- .update-gh-pages.sh
script: 
- make test
